apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 namespace: default
 name: cluster-pod-writer
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "patch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 namespace: default
 name: cluster-secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 namespace: default
 name: cluster-secret-writer
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "patch", "update", "delete"]